# Generated by Django 5.2.13 on 2026-05-05 08:12

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0002_alter_user_options_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("farmer", "Farmer"),
                    ("extension_agent", "Extension Agent"),
                    ("expert", "Expert"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
