"""
Constants for the project.
"""

PLATEAU_LGAS = [
    "Barkin Ladi",
    "Bassa",
    "Bokkos",
    "Jos East",
    "Jos North",
    "Jos South",
    "Kanam",
    "Kanke",
    "Langtang North",
    "Langtang South",
    "Mangu",
    "Mikang",
    "Pankshin",
    "Qua'an Pan",
    "Riyom",
    "Shendam",
    "Wase",
]

PLATEAU_LGA_WARDS = {
    "Barkin Ladi": [
        "Barakin Ladi",
        "Gassa/Sho",
        "Gindin Akwati",
        "Lobiring",
        "Marit/Mazat",
        "Rafan",
        "Tafan",
        "Zabot",
    ],
    "Bassa": [
        "Buhit",
        "Buji",
        "Gabia",
        "Gurum",
        "Jengre",
        "Kadamo",
        "Kakkek",
        "Kasuru",
        "Kimakpa",
        "Kishika",
        "Mafara",
        "Rimi",
        "Ta'agbe",
        "Tahu",
        "Zabolo",
        "Zobwo",
    ],
    "Bokkos": [
        "Bokkos",
        "Butura",
        "Daffo",
        "Damwai",
        "Kwatas",
        "Mangor",
        "Manguna",
        "Mbar/Mangar",
        "Mushere Central",
        "Mushere West",
        "Richa",
        "Sha",
        "Tangur",
        "Toff",
    ],
    "Jos East": [
        "Federe",
        "Fobur 'A'",
        "Fobur 'B'",
        "Fursum",
        "Jarawan Kogi",
        "Mai Gemu",
        "Maijuju",
        "Shere East",
        "Shere West",
        "Zandi",
    ],
    "Jos North": [
        "Abba Na Shehu",
        "Ali Kazaure",
        "Gangare",
        "Garba Daho",
        "Ibrahim Katsina",
        "Jenta Adamu",
        "Jenta Apata",
        "Jos Jarawa",
        "Naraguta 'A'",
        "Naraguta 'B'",
        "Sarkin Arab",
        "Tafawa Balewa",
        "Tudun Wada – Kabong",
        "Vanderpuye",
    ],
    "Jos South": [
        "Bukuru",
        "Du",
        "Giring",
        "Gyel 'A'",
        "Gyel 'B'",
        "Kuru 'A'",
        "Kuru 'B'",
        "Shen",
        "Turu",
        "Vwang",
        "Zawan 'A'",
        "Zawan 'B'",
    ],
    "Kanam": [
        "Birbyang",
        "Dengi",
        "Dugub",
        "Gagdib",
        "Garga",
        "Gumsher",
        "Gwamlar",
        "Jarmai",
        "Jom",
        "Kanam",
        "Kantana",
        "Kunkyam",
        "Munbutbo",
        "Namaran",
    ],
    "Kanke": [
        "Ampang East",
        "Amper Chika 'A'",
        "Amper Chika 'B'",
        "Amper Seri",
        "Dawaki",
        "Garram",
        "Kabwir Pada",
        "Kabwir/Gyangyang",
        "Langshi",
        "Nemel",
    ],
    "Langtang North": [
        "Funyalang",
        "Jat",
        "Keller",
        "Kuffen",
        "Kwallak",
        "Kwande",
        "Lipchok",
        "Mban/Zamko",
        "Nyer",
        "Pajat",
        "Pil Gani",
        "Pishe/Yashi",
        "Reak",
        "Waroh",
    ],
    "Langtang South": [
        "Dadin Kowa",
        "Fajul",
        "Gamakai",
        "Lashel",
        "Mabudi",
        "Magama",
        "Sabon Gida",
        "Talgwang",
        "Timbol",
        "Turaki",
    ],
    "Mangu": [
        "Ampang West",
        "Chanso",
        "Gindiri I",
        "Gindiri II",
        "Jannaret",
        "Jipal/Chakfem",
        "Kadunu",
        "Kerang",
        "Kombun",
        "Langai",
        "Mangu I",
        "Mangu II",
        "Mangu Halle",
        "Mangun",
        "Pan Yam",
        "Pushit",
    ],
    "Mikang": [
        "Baltep",
        "Garkawa Central",
        "Garkawa North",
        "Garkawa North East",
        "Koenoem 'A'",
        "Koenoem 'B'",
        "Lalin",
        "Piapung 'A'",
        "Piapung 'B'",
        "Tunkus",
    ],
    "Pankshin": [
        "Chip",
        "Dok-Pai",
        "Fier",
        "Jiblik",
        "Kadung",
        "Kangshu",
        "Lankang",
        "Pankshin Central",
        "Pankshin Chigwong",
        "Pankshin South (Belning)",
        "Tal",
        "Wokkos",
    ],
    "Qua'an Pan": [
        "Bwall",
        "Doemak-Goechim",
        "Doemak-Koplong",
        "Dokan Kasuwa",
        "Kurgwi",
        "Kwa",
        "Kwalla Moeda",
        "Kwalla Yitla'ar",
        "Kwande",
        "Kwang",
        "Namu",
    ],
    "Riyom": [
        "Attakar",
        "Bum",
        "Danto",
        "Jol/Kwi",
        "Ra-Hoss",
        "Rim",
        "Riyom",
        "Sharubutu",
        "Sopp",
        "Ta-Hoss",
    ],
    "Shendam": [
        "Derteng",
        "Kalong",
        "Kurungbau (A)",
        "Kurungbau (B)",
        "Moekat",
        "Pangshom",
        "Poeship",
        "Shendam Central (A)",
        "Shendam Central (B)",
        "Shimankar",
        "Yelwa",
    ],
    "Wase": [
        "Bashar",
        "Danbiram",
        "Gudus",
        "Kadarko",
        "Kumbong",
        "Kumbur",
        "Kuyambana",
        "Mavo",
        "Nyalum/Kampani",
        "Saluwe",
        "Wase Tofa",
        "Yola Wakat",
    ],
}
