# Generated by Django 6.0.4 on 2026-04-22 10:53

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LGA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("state", models.CharField(default="Plateau", max_length=100)),
            ],
            options={
                "verbose_name": "LGA",
                "verbose_name_plural": "LGAs",
                "ordering": ["name"],
            },
        ),
    ]
