# Generated by Django 5.2.13 on 2026-05-29 07:58

# django_packages
import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True once the whitelisted email completes registration.",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who added this entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_whitelist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Whitelist",
                "verbose_name_plural": "Dashboard Whitelist",
            },
        ),
    ]
