"""
Constants for the farms app.
"""

PLATEAU_CROPS = [
    "Maize",
    "Tomato",
    "Yam",
    "Cassava",
    "Rice",
    "Soybean",
    "Groundnut",
    "Sorghum",
    "Millet",
    "Sweet Potato",
    "Cowpea",
    "Pepper",
    "Onion",
    "Ginger",
    "Cabbage",
    "Carrot",
    "Spinach",
    "Irish Potato",
    "Wheat",
    "Sesame",
    "Sugarcane",
    "Cotton",
    "Banana",
    "Plantain",
    "Orange",
    "Mango",
]

FARM_ANIMALS = [
    "Cattle",
    "Goat",
    "Sheep",
    "Pig",
    "Chicken",
    "Turkey",
    "Duck",
    "Guinea Fowl",
    "Rabbit",
    "Fish (Tilapia)",
    "Fish (Catfish)",
    "Bee (Beekeeping)",
    "Quail",
    "Donkey",
]


# Maps each crop name to a list of known varieties grown in Plateau State / Nigeria.
CROP_VARIETIES = {
    "Maize": [
        "SAMMAZ 15",
        "SAMMAZ 29",
        "OBA Super 2",
        "TZBSR-W",
        "ACR 94 TZL COMP3-W",
        "Swan 1",
        "Local Yellow",
    ],
    "Tomato": [
        "Roma VF",
        "UC82B",
        "Beske",
        "Tropimech",
        "Rodo (Plum)",
        "Falcon F1",
        "Cobra F1",
    ],
    "Yam": [
        "Dioscorea rotundata (White Yam)",
        "Dioscorea cayenensis (Yellow Yam)",
        "Dioscorea alata (Water Yam)",
        "Pona",
        "Amula",
    ],
    "Cassava": [
        "TMS 30572",
        "TMS 98/0505",
        "UMUCASS 36 (Poundable)",
        "UMUCASS 37",
        "Game Changer",
        "Obasanjo-2",
    ],
    "Rice": [
        "FARO 44",
        "FARO 52",
        "FARO 60",
        "Sipi",
        "NERICA 1",
        "NERICA 4",
        "Igbemo",
    ],
    "Soybean": [
        "TGX 1448-2E",
        "TGX 1740-2F",
        "TGX 1835-10E",
        "Samsoy 2",
        "Samsoy 4",
    ],
    "Groundnut": [
        "SAMNUT 21",
        "SAMNUT 22",
        "SAMNUT 24",
        "SAMNUT 26",
        "Kano Local",
    ],
    "Sorghum": [
        "SAMSORG 14",
        "SAMSORG 17",
        "SAMSORG 40",
        "Farafara",
        "Kaura",
        "SK 5912",
    ],
    "Millet": [
        "SOSAT-C88",
        "LCIC 9702",
        "Maiwa",
        "Ex-Borno",
        "Tafi",
    ],
    "Sweet Potato": [
        "UMUSPO 3",
        "UMUSPO 5",
        "Ex-Igbariam",
        "Centennial",
        "Tanzania",
    ],
    "Cowpea": [
        "IT97K-499-35",
        "IT99K-573-1-1",
        "Sampea 20",
        "Sampea 20-T",
        "Oloyin",
        "Ife Brown",
    ],
    "Pepper": [
        "Tatase (Bell Pepper)",
        "Sombo (Cayenne)",
        "Rodo (Habanero)",
        "Shombo",
        "Nsukka Yellow",
    ],
    "Onion": [
        "Bende Local",
        "Kano Red",
        "BVOG 1",
        "Violet de Galmi",
        "Gusau Local",
    ],
    "Ginger": [
        "Tafin Giwa",
        "Yatsun Biri",
        "Lafia Local",
        "Plateau Early",
    ],
    "Cabbage": [
        "Copenhagen Market",
        "Gloria",
        "Oxylus F1",
        "Drumhead",
    ],
    "Carrot": [
        "Nantes",
        "Chantenay",
        "Danvers",
        "Plateau Local",
    ],
    "Spinach": [
        "Bloomsdale",
        "Savoy",
        "Nigerian Spinach (Efo Tete)",
        "Flat Leaf",
    ],
    "Irish Potato": [
        "Nicola",
        "Diamant",
        "Valor",
        "Marinera",
        "Plateau Local",
    ],
    "Wheat": [
        "NIwheat 1",
        "NIwheat 2",
        "Atilla",
        "Krichauff",
    ],
    "Sesame": [
        "E8",
        "NCRIBEN-01E",
        "Yandev 55",
        "Local White",
    ],
    "Sugarcane": [
        "NCS 001",
        "NCS 002",
        "Co 957",
        "Local Red",
    ],
    "Cotton": [
        "SAMCOT 8",
        "SAMCOT 9",
        "SAMCOT 10",
        "Allen",
    ],
    "Banana": [
        "Cavendish",
        "Grand Naine",
        "Williams Hybrid",
        "Local Dwarf",
    ],
    "Plantain": [
        "False Horn",
        "True Horn",
        "French Plantain",
        "Agbagba",
        "Obino l'Ewai",
    ],
    "Orange": [
        "Valencia",
        "Navel",
        "Blood Orange",
        "Local Sweet",
    ],
    "Mango": [
        "Keitt",
        "Kent",
        "Alphonso",
        "Julie",
        "Peter",
        "Sheri",
        "Local Plateau",
    ],
}
