# Generated by Django 6.0.4 on 2026-04-11 18:51

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SingleVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.CharField(
                        help_text="Bible book name exactly as used by the helloao.org API, e.g. '1John', 'Genesis', 'Psalms'.",
                        max_length=50,
                    ),
                ),
                (
                    "chapter",
                    models.PositiveSmallIntegerField(
                        help_text="Chapter number within the book."
                    ),
                ),
                (
                    "verse",
                    models.PositiveSmallIntegerField(
                        help_text="Verse number within the chapter. Always a single verse, never a range."
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Full scripture text for this verse, sourced from the external Bible API."
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        choices=[
                            ("ENGWEBP", "World English Bible"),
                            ("eng_kjv", "King James Version"),
                        ],
                        default="eng_kjv",
                        help_text="Bible translation key, e.g. 'ENGWEBP' or 'eng_kjv'.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Single Verse",
                "verbose_name_plural": "Single Verses",
                "ordering": ["book", "chapter", "verse"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("book", "chapter", "verse", "version"),
                        name="unique_single_verse_per_version",
                    )
                ],
            },
        ),
    ]
