# Generated by Django 6.0.4 on 2026-04-12 06:47

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verses", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="singleverse",
            index=models.Index(
                fields=["book", "chapter", "verse"], name="verses_sing_book_d9b7cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="singleverse",
            index=models.Index(
                fields=["version"], name="verses_sing_version_154cbf_idx"
            ),
        ),
    ]
