# Generated by Django 6.0.4 on 2026-04-12 06:59

# django_packages
import django.core.validators

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verses", "0002_singleverse_verses_sing_book_d9b7cf_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singleverse",
            name="chapter",
            field=models.PositiveSmallIntegerField(
                help_text="Chapter number within the book.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="singleverse",
            name="verse",
            field=models.PositiveSmallIntegerField(
                help_text="Verse number within the chapter. Always a single verse, never a range.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="singleverse",
            name="version",
            field=models.CharField(
                choices=[
                    ("ENGWEBP", "World English Bible"),
                    ("eng_kjv", "King James Version"),
                ],
                default="eng_kjv",
                help_text="Bible translation key, e.g. 'ENGWEBP' or 'eng_kjv'.",
                max_length=10,
            ),
        ),
    ]
