# Generated by Django 6.0.4 on 2026-04-12 07:20

# django_packages
import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verses", "0003_alter_singleverse_chapter_alter_singleverse_verse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user who first added this selection to the database.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_memory_verses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verse_end",
                    models.ForeignKey(
                        blank=True,
                        help_text="The last verse of this selection. Null when the selection is a single verse.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memory_verses_as_end",
                        to="verses.singleverse",
                    ),
                ),
                (
                    "verse_start",
                    models.ForeignKey(
                        help_text="The first (or only) verse of this selection.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memory_verses_as_start",
                        to="verses.singleverse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory Verse",
                "verbose_name_plural": "Memory Verses",
                "ordering": [
                    "verse_start__book",
                    "verse_start__chapter",
                    "verse_start__verse",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("verse_start", "verse_end"),
                        name="unique_memory_verse_selection",
                    )
                ],
            },
        ),
    ]
