# Generated by Django 6.0.4 on 2026-04-12 07:23

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verses", "0004_memoryverse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "ordering": ["name"],
            },
        ),
    ]
