# Generated by Django 6.0.4 on 2026-04-12 11:30

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verses", "0005_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryverse",
            name="verse_end",
            field=models.ForeignKey(
                blank=True,
                help_text="The last verse of this selection. Null when the selection is a single verse.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_verses_as_end",
                to="verses.singleverse",
            ),
        ),
        migrations.AlterField(
            model_name="memoryverse",
            name="verse_start",
            field=models.ForeignKey(
                help_text="The first (or only) verse of this selection.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_verses_as_start",
                to="verses.singleverse",
            ),
        ),
    ]
