# Generated by Django 6.0.4 on 2026-04-12 12:22

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verses", "0006_alter_memoryverse_verse_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryverse",
            name="topics",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional topic classifications for this verse selection.",
                related_name="memory_verses",
                to="verses.topic",
            ),
        ),
    ]
