# Generated by Django 6.0.4 on 2026-04-12 18:09

# django_packages
import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verses", "0007_memoryverse_topics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVerse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Queue position within the user's verse list. Lower values appear first. Not required to be contiguous or positive.",
                    ),
                ),
                (
                    "tally",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cumulative number of times the user has recited this verse.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "memory_verse",
                    models.ForeignKey(
                        help_text="The memory verse this record refers to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_verses",
                        to="verses.memoryverse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this record.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_verses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Verse",
                "verbose_name_plural": "User Verses",
                "ordering": ["user", "order"],
                "indexes": [
                    models.Index(
                        fields=["user", "order"], name="user_verse_user_order_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "memory_verse"),
                        name="unique_user_verse_per_user",
                    )
                ],
            },
        ),
    ]
