# Generated by Django 6.0.4 on 2026-04-14 06:16

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verses", "0008_userverse"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverse",
            name="last_practiced_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="userverse",
            name="learned_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="userverse",
            name="topics",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional user-defined topic overrides for this verse. When set, these replace the memory verse's system-wide topics for this user. Leave empty to inherit from the memory verse.",
                related_name="user_verses",
                to="verses.topic",
            ),
        ),
    ]
