# Generated by Django 6.0.4 on 2026-04-19 06:45

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verses", "0009_userverse_last_practiced_at_userverse_learned_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverse",
            name="last_learned_at",
            field=models.DateTimeField(
                help_text="When the user last recited this verse.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userverse",
            name="learned_at",
            field=models.DateTimeField(
                help_text="When the user first began learning this verse.", null=True
            ),
        ),
    ]
