# Generated by Django 6.0.4 on 2026-04-22 12:20

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        ("profiles", "0002_alter_farmerprofile_lga_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="profiles.extensionagentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="answer_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="questions.answer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Image",
                "verbose_name_plural": "Answer Images",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "crop_concern",
                    models.CharField(
                        blank=True,
                        help_text="The crop this question is about, e.g. Maize, Tomato.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("answered", "Answered"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "is_escalated",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True when an agent escalates this question to an expert.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        help_text="The farm this question relates to, if applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="farms.farm",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="profiles.farmerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Escalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="The agent's explanation for why this question needs expert attention."
                    ),
                ),
                ("escalated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "escalated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="profiles.extensionagentprofile",
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escalation",
                "verbose_name_plural": "Escalations",
                "ordering": ["-escalated_at"],
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="questions.question",
            ),
        ),
        migrations.CreateModel(
            name="QuestionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="question_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Image",
                "verbose_name_plural": "Question Images",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AnswerHelpfulness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_helpful", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpfulness_ratings",
                        to="questions.answer",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpfulness_ratings",
                        to="profiles.farmerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer Helpfulness",
                "verbose_name_plural": "Answer Helpfulness Ratings",
                "unique_together": {("answer", "farmer")},
            },
        ),
    ]
