# Generated by Django 6.0.4 on 2026-05-03 09:37

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0005_alter_farm_image"),
        ("questions", "0002_alter_answerimage_image_alter_questionimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="crop_concern",
            field=models.ForeignKey(
                blank=True,
                help_text="The crop this question is about.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="farms.crop",
            ),
        ),
    ]
