# Generated by Django 6.0.4 on 2026-05-03 09:52

# django_packages
from django.db import migrations, models

# other_apps_packages
import core.common.utils
import core.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_alter_question_crop_concern"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionimage",
            name="question",
        ),
        migrations.AddField(
            model_name="answer",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An optional image to help illustrate the answer.",
                null=True,
                upload_to=core.common.utils.file_upload_path,
                validators=[
                    core.common.validators.validate_image_size,
                    core.common.validators.validate_image_format,
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="An optional image to help illustrate the question.",
                null=True,
                upload_to=core.common.utils.file_upload_path,
                validators=[
                    core.common.validators.validate_image_size,
                    core.common.validators.validate_image_format,
                ],
            ),
        ),
        migrations.DeleteModel(
            name="AnswerImage",
        ),
        migrations.DeleteModel(
            name="QuestionImage",
        ),
    ]
