# Generated by Django 5.2.13 on 2026-05-05 08:12

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_remove_questionimage_question_answer_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="answerhelpfulness",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="escalation",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
