# Generated by Django 5.2.13 on 2026-05-13 14:54

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0008_farm_ward"),
        ("questions", "0005_alter_answer_id_alter_answerhelpfulness_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="animal_concern",
            field=models.ForeignKey(
                blank=True,
                help_text="The animal/livestock this question is about.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="farms.animal",
            ),
        ),
    ]
