# Generated by Django 6.0.4 on 2026-04-22 13:28

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        ("profiles", "0002_alter_farmerprofile_lga_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FarmVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField()),
                (
                    "purpose",
                    models.CharField(
                        help_text="Brief description of the reason for the visit.",
                        max_length=255,
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True,
                        help_text="What the agent observed during the visit.",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Advice or action points given to the farmer.",
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether a follow-up visit is needed.",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True,
                        help_text="Target date for the follow-up visit, if required.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farm_visits",
                        to="profiles.extensionagentprofile",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Visit",
                "verbose_name_plural": "Farm Visits",
                "ordering": ["-visit_date"],
            },
        ),
    ]
