# Generated by Django 5.2.13 on 2026-05-13 19:50

# django_packages
import django.core.validators
import django.db.models.deletion

from django.db import migrations, models

# other_apps_packages
import core.common.utils
import core.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0009_cropvariety"),
        ("profiles", "0003_alter_extensionagentprofile_id_and_more"),
        ("visits", "0002_alter_farmvisit_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(
                        help_text="The calendar date when the visit took place."
                    ),
                ),
                (
                    "visit_time",
                    models.TimeField(
                        blank=True,
                        help_text="The exact time the visit started, if available.",
                        null=True,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("routine_monitoring", "Routine Monitoring"),
                            ("problem_diagnosis", "Problem Diagnosis"),
                            ("advisory_follow_up", "Advisory Follow-up"),
                            ("pest_disease_inspection", "Pest/Disease Inspection"),
                            ("soil_assessment", "Soil Assessment"),
                            ("fertilizer_recommendation", "Fertilizer Recommendation"),
                            ("pre_harvest_inspection", "Pre-Harvest Inspection"),
                            ("farm_verification", "Farm Verification"),
                            ("yield_assessment", "Yield Assessment"),
                            ("other", "Other"),
                        ],
                        default="routine_monitoring",
                        help_text="The main reason for carrying out the visit.",
                        max_length=255,
                    ),
                ),
                (
                    "purpose_other",
                    models.CharField(
                        blank=True,
                        help_text="Additional details when the purpose is marked as 'Other'.",
                        max_length=255,
                    ),
                ),
                (
                    "farm_photo",
                    models.ImageField(
                        blank=True,
                        help_text="A photo taken of the farm during the visit.",
                        null=True,
                        upload_to=core.common.utils.file_upload_path,
                        validators=[
                            core.common.validators.validate_image_size,
                            core.common.validators.validate_image_format,
                        ],
                    ),
                ),
                (
                    "pest_photo",
                    models.ImageField(
                        blank=True,
                        help_text="A photo showing any pests or disease signs observed.",
                        null=True,
                        upload_to=core.common.utils.file_upload_path,
                        validators=[
                            core.common.validators.validate_image_size,
                            core.common.validators.validate_image_format,
                        ],
                    ),
                ),
                (
                    "soil_photo",
                    models.ImageField(
                        blank=True,
                        help_text="A photo of the soil condition taken during the visit.",
                        null=True,
                        upload_to=core.common.utils.file_upload_path,
                        validators=[
                            core.common.validators.validate_image_size,
                            core.common.validators.validate_image_format,
                        ],
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Any supporting documents or files related to the visit.",
                        null=True,
                        upload_to=core.common.utils.file_upload_path,
                    ),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether another visit is needed.",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True,
                        help_text="The scheduled date for the follow-up visit, if required.",
                        null=True,
                    ),
                ),
                (
                    "priority_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        help_text="Indicates how urgent the follow-up or issue is.",
                        max_length=10,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("advice_provided", "Advice Provided Successfully"),
                            ("escalated", "Escalated to Specialist"),
                            ("verified", "Verification Completed"),
                            ("follow_up", "Follow-up Scheduled"),
                        ],
                        help_text="The final result or status of the visit.",
                        max_length=30,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this visit record was created.",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The extension agent who carried out the visit.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="profiles.extensionagentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date", "-visit_time"],
            },
        ),
        migrations.CreateModel(
            name="VisitCropAnalysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("planting", "Planting"),
                            ("vegetative", "Vegetative"),
                            ("flowering", "Flowering"),
                            ("fruiting", "Fruiting"),
                            ("harvesting", "Harvesting"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date_planted", models.DateField(blank=True, null=True)),
                ("expected_harvest_date", models.DateField(blank=True, null=True)),
                (
                    "crop_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("soil_moisture_status", models.CharField(blank=True, max_length=255)),
                ("weed_presence", models.BooleanField(default=False)),
                ("rainfall_situation", models.TextField(blank=True)),
                (
                    "observations",
                    models.TextField(
                        blank=True,
                        help_text="General observations made about this crop.",
                    ),
                ),
                ("other_problem", models.TextField(blank=True)),
                (
                    "recommendations",
                    models.TextField(
                        blank=True, help_text="Recommendations made for this crop."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_analyses",
                        to="farms.crop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_analyses",
                        to="farms.farm",
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="farms.cropvariety",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_analyses",
                        to="visits.visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PestIncidence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pest", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pest_incidences",
                        to="visits.visitcropanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropIssue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("poor_germination", "Poor Germination"),
                            ("yellow_leaves", "Yellow Leaves"),
                            ("stunted_growth", "Stunted Growth"),
                            ("pest_attack", "Pest Attack"),
                            ("disease_infection", "Disease Infection"),
                            ("drought_stress", "Drought Stress"),
                            ("waterlogging", "Waterlogging"),
                            ("fertilizer_misapplication", "Fertilizer Misapplication"),
                            ("low_plant_population", "Low Plant Population"),
                        ],
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="visits.visitcropanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CropAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("apply_fertilizer", "Apply Fertilizer"),
                            ("spray_pesticide", "Spray Pesticide"),
                            ("weed_immediately", "Weed Immediately"),
                            ("irrigate", "Irrigate"),
                            ("replant", "Replant Missing Stands"),
                            ("improve_drainage", "Improve Drainage"),
                            ("contact_specialist", "Contact Specialist"),
                            ("monitor", "Monitor for One Week"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional detail for this action."
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="visits.visitcropanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitFarmerFeedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advice_understood_by_farmer", models.BooleanField(default=True)),
                (
                    "farmer_satisfaction_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("farmer_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_feedback",
                        to="visits.visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitIssue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="A short title describing the issue found during the visit.",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A detailed explanation of the issue, if needed.",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="How serious the issue is, from low to critical.",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this issue was recorded.",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        help_text="The visit this issue was identified in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="visits.visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitLivestockAnalysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "breed_or_variety",
                    models.CharField(
                        blank=True,
                        help_text="Breed or local variety name, if known.",
                        max_length=100,
                    ),
                ),
                (
                    "production_purpose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("meat", "Meat"),
                            ("dairy", "Dairy"),
                            ("eggs", "Eggs"),
                            ("draught", "Draught / Work"),
                            ("breeding", "Breeding"),
                            ("mixed", "Mixed"),
                            ("other", "Other"),
                        ],
                        help_text="The primary reason this animal is kept on the farm.",
                        max_length=20,
                    ),
                ),
                (
                    "housing_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("extensive", "Extensive (Free-Range)"),
                            ("semi_intensive", "Semi-Intensive"),
                            ("intensive", "Intensive (Confined)"),
                            ("zero_grazing", "Zero Grazing"),
                        ],
                        help_text="How the animals are housed or managed.",
                        max_length=20,
                    ),
                ),
                (
                    "total_population",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Approximate total number of animals of this species on the farm.",
                        null=True,
                    ),
                ),
                (
                    "number_sick",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of animals showing signs of illness at the time of the visit.",
                        null=True,
                    ),
                ),
                (
                    "number_dead_this_period",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Deaths recorded since the last visit or in the current period.",
                        null=True,
                    ),
                ),
                (
                    "overall_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        help_text="Agent's overall assessment of the herd or flock condition.",
                        max_length=20,
                    ),
                ),
                (
                    "body_condition_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Body condition score on a 1–5 scale, if assessed.",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "feed_availability",
                    models.CharField(
                        blank=True,
                        help_text="Description of the feed/fodder situation at the time of the visit.",
                        max_length=255,
                    ),
                ),
                (
                    "water_availability",
                    models.CharField(
                        blank=True,
                        help_text="Description of water source availability and quality.",
                        max_length=255,
                    ),
                ),
                (
                    "vaccination_status",
                    models.CharField(
                        blank=True,
                        help_text="Current vaccination status or last vaccination date, if known.",
                        max_length=255,
                    ),
                ),
                (
                    "deworming_status",
                    models.CharField(
                        blank=True,
                        help_text="Last deworming date or treatment history, if known.",
                        max_length=255,
                    ),
                ),
                (
                    "ectoparasite_presence",
                    models.BooleanField(
                        default=False,
                        help_text="Whether ticks, lice, mites, or other ectoparasites were observed.",
                    ),
                ),
                (
                    "general_observations",
                    models.TextField(
                        blank=True,
                        help_text="General free-text observations about the livestock during this visit.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal",
                    models.ForeignKey(
                        help_text="The species of animal being assessed.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_analyses",
                        to="farms.animal",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        help_text="The visit during which this livestock analysis was recorded.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livestock_analyses",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit Livestock Analysis",
                "verbose_name_plural": "Visit Livestock Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LivestockIssue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("disease_outbreak", "Disease Outbreak"),
                            ("parasite_infestation", "Parasite Infestation"),
                            ("nutritional_deficiency", "Nutritional Deficiency"),
                            ("poor_body_condition", "Poor Body Condition"),
                            ("reproductive_failure", "Reproductive Failure"),
                            ("high_mortality", "High Mortality Rate"),
                            ("feed_shortage", "Feed / Fodder Shortage"),
                            ("water_shortage", "Water Shortage"),
                            ("poor_housing", "Poor Housing / Shelter"),
                            ("injury", "Injury or Wound"),
                            ("biosecurity_breach", "Biosecurity Breach"),
                            ("other", "Other"),
                        ],
                        help_text="The category of problem observed.",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional detail about this issue."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        help_text="The livestock analysis this issue was identified in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="visits.visitlivestockanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livestock Issue",
                "verbose_name_plural": "Livestock Issues",
                "ordering": ["issue_type"],
            },
        ),
        migrations.CreateModel(
            name="LivestockDiseaseIncidence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease_name",
                    models.CharField(
                        help_text="Name of the disease or condition observed or suspected.",
                        max_length=150,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        help_text="How severe this disease incidence is.",
                        max_length=10,
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("suspected", "Suspected"),
                            ("probable", "Probable"),
                            ("confirmed", "Confirmed (Lab or Vet)"),
                        ],
                        default="suspected",
                        help_text="How certain the agent is about this diagnosis.",
                        max_length=15,
                    ),
                ),
                (
                    "symptoms_observed",
                    models.TextField(
                        blank=True,
                        help_text="Clinical signs or symptoms noted in the affected animals.",
                    ),
                ),
                (
                    "animals_affected_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated number of animals showing signs of this condition.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        help_text="The livestock analysis this disease incidence belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_incidences",
                        to="visits.visitlivestockanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livestock Disease Incidence",
                "verbose_name_plural": "Livestock Disease Incidences",
                "ordering": ["-severity"],
            },
        ),
        migrations.CreateModel(
            name="LivestockAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("vaccinate", "Vaccinate Animals"),
                            ("deworm", "Administer Dewormer"),
                            ("treat_ectoparasites", "Treat for Ectoparasites"),
                            ("isolate_sick", "Isolate Sick Animals"),
                            ("improve_feed", "Improve Feed / Nutrition"),
                            ("improve_water", "Improve Water Supply"),
                            ("improve_housing", "Improve Housing / Shelter"),
                            ("call_vet", "Call a Veterinarian"),
                            ("submit_sample", "Submit Sample for Laboratory Testing"),
                            ("cull_animals", "Cull Affected Animals"),
                            ("apply_biosecurity", "Apply Biosecurity Measures"),
                            ("monitor", "Monitor for One Week"),
                            ("other", "Other"),
                        ],
                        help_text="The type of recommended intervention.",
                        max_length=50,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional detail or instructions for carrying out this action.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        help_text="The livestock analysis this action was recommended for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="visits.visitlivestockanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livestock Action",
                "verbose_name_plural": "Livestock Actions",
                "ordering": ["action_type"],
            },
        ),
        migrations.CreateModel(
            name="VisitObservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        help_text="A detailed note describing what was observed during the visit."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this observation was recorded.",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        help_text="The visit this observation belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="visits.visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        help_text="Advice or action steps given to the farmer during the visit."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this recommendation was recorded.",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        help_text="The visit this recommendation belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="visits.visit",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="FarmVisit",
        ),
    ]
