# Generated by Django 5.2.13 on 2026-05-13 20:41

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0009_cropvariety"),
        ("visits", "0003_visit_visitcropanalysis_pestincidence_cropissue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                help_text="The farm which was visited",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="farms.farm",
            ),
        ),
    ]
