# Generated by Django 5.2.13 on 2026-05-14 03:55

# django_packages
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0004_visit_farm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitcropanalysis",
            name="farm",
        ),
    ]
