# Generated by Django 6.0.4 on 2026-04-22 13:28

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0002_alter_farmerprofile_lga_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisoryPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("video", "Video"),
                            ("infographic", "Infographic"),
                            ("other", "Other"),
                        ],
                        default="article",
                        max_length=20,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to an embedded video, e.g. a YouTube or Vimeo URL.",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Optional file upload such as a PDF guide or data sheet.",
                        null=True,
                        upload_to="advisory_attachments/",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="advisory_covers/"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags, e.g. 'maize, pest control, irrigation'.",
                        max_length=500,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set automatically when the post is first published.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisory_posts",
                        to="profiles.extensionagentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advisory Post",
                "verbose_name_plural": "Advisory Posts",
                "ordering": ["-created_at"],
            },
        ),
    ]
