# Generated by Django 5.2.13 on 2026-05-05 10:06

# django_packages
from django.db import migrations

# third_party_packages
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("advisory", "0002_alter_advisorypost_id"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advisorypost",
            name="tags",
        ),
        migrations.AddField(
            model_name="advisorypost",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
