# Generated by Django 6.0.4 on 2026-04-22 11:32

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("profiles", "0002_alter_farmerprofile_lga_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Street address or nearest landmark."
                    ),
                ),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Farm size in hectares.",
                        max_digits=8,
                    ),
                ),
                (
                    "primary_crop",
                    models.CharField(
                        help_text="e.g. Maize, Tomato, Yam.", max_length=100
                    ),
                ),
                (
                    "other_crops",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of other crops grown on the farm.",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Optional GPS latitude for geo-tagging.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Optional GPS longitude for geo-tagging.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True by an extension agent after physical verification.",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of when the farm was verified.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to="profiles.farmerprofile",
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farms",
                        to="common.lga",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The extension agent who verified this farm.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_farms",
                        to="profiles.extensionagentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm",
                "verbose_name_plural": "Farms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="farm_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Image",
                "verbose_name_plural": "Farm Images",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
