# Generated by Django 6.0.4 on 2026-04-28 11:36

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Crop",
                "verbose_name_plural": "Crops",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="farm",
            name="other_crops",
        ),
        migrations.AlterField(
            model_name="farm",
            name="primary_crop",
            field=models.ForeignKey(
                blank=True,
                help_text="The main crop grown on this farm.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_farms",
                to="farms.crop",
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="other_crops",
            field=models.ManyToManyField(
                blank=True,
                help_text="Additional crops grown on this farm.",
                related_name="secondary_farms",
                to="farms.crop",
            ),
        ),
    ]
