# Generated by Django 6.0.4 on 2026-04-28 12:07

# django_packages
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_crop_remove_farm_other_crops_alter_farm_primary_crop_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farm",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="farm",
            name="longitude",
        ),
    ]
