# Generated by Django 6.0.4 on 2026-04-30 11:45

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0003_remove_farm_latitude_remove_farm_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="A single representative image of the farm.",
                null=True,
                upload_to="farm_images/",
            ),
        ),
        migrations.DeleteModel(
            name="FarmImage",
        ),
    ]
