# Generated by Django 6.0.4 on 2026-04-30 13:43

# django_packages
from django.db import migrations, models

# other_apps_packages
import core.common.utils
import core.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0004_farm_image_delete_farmimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="A single representative image of the farm.",
                null=True,
                upload_to=core.common.utils.file_upload_path,
                validators=[
                    core.common.validators.validate_image_size,
                    core.common.validators.validate_image_format,
                ],
            ),
        ),
    ]
