# Generated by Django 5.2.13 on 2026-05-05 08:12

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0005_alter_farm_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
