# Generated by Django 5.2.13 on 2026-05-05 11:26

# django_packages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0006_alter_crop_id_alter_farm_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Animal",
                "verbose_name_plural": "Animals",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="farm",
            name="animals",
            field=models.ManyToManyField(
                blank=True,
                help_text="Livestock or animals kept on this farm.",
                related_name="farms",
                to="farms.animal",
            ),
        ),
    ]
