# Generated by Django 5.2.13 on 2026-05-11 08:15

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_ward"),
        ("farms", "0007_animal_farm_animals"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="ward",
            field=models.ForeignKey(
                blank=True,
                help_text="The ward within the LGA where this farm is located.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farms",
                to="common.ward",
            ),
        ),
    ]
