# Generated by Django 5.2.13 on 2026-05-13 19:50

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0008_farm_ward"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropVariety",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the crop variety (e.g., specific type or strain).",
                        max_length=100,
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        help_text="The crop this variety belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="varieties",
                        to="farms.crop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crop Variety",
                "verbose_name_plural": "Crop Varieties",
                "ordering": ["name"],
                "unique_together": {("crop", "name")},
            },
        ),
    ]
