# Generated by Django 6.0.4 on 2026-04-22 10:44

# django_packages
import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LGA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("state", models.CharField(default="Plateau", max_length=100)),
            ],
            options={
                "verbose_name": "LGA",
                "verbose_name_plural": "LGAs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExtensionAgentWhitelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True once the whitelisted email completes registration.",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who added this entry.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whitelist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Extension Agent Whitelist",
                "verbose_name_plural": "Extension Agent Whitelist",
            },
        ),
        migrations.CreateModel(
            name="FarmerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="farmers",
                        to="profiles.lga",
                    ),
                ),
            ],
            options={
                "verbose_name": "Farmer Profile",
                "verbose_name_plural": "Farmer Profiles",
            },
        ),
        migrations.CreateModel(
            name="ExtensionAgentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "agency_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. ADP – Agricultural Development Programme",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_lgas",
                    models.ManyToManyField(
                        blank=True, related_name="assigned_agents", to="profiles.lga"
                    ),
                ),
            ],
            options={
                "verbose_name": "Extension Agent Profile",
                "verbose_name_plural": "Extension Agent Profiles",
            },
        ),
    ]
