# Generated by Django 6.0.4 on 2026-04-22 10:53

# django_packages
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerprofile",
            name="lga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farmers",
                to="common.lga",
            ),
        ),
        migrations.AlterField(
            model_name="extensionagentprofile",
            name="assigned_lgas",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_agents", to="common.lga"
            ),
        ),
        migrations.DeleteModel(
            name="LGA",
        ),
    ]
